export const CardData = [
  {
    location: "Abiansemal, Indonesia",
    rating: "4.87",
    km: "5,807",
    availability: "2-7 Jul",
    price: "28,734",
    img: "./images/1.png",
  },
  {
    location: "Chittorgarh, India",
    rating: "New",
    km: "434",
    availability: "1-6 Sept",
    price: "3,400",
    img: "./images/2.png",
  },
  {
    location: "Nisseldal, Norway",
    rating: "4.93",
    km: "7001",
    availability: "18-23 Sept",
    price: "8,400",
    img: "./images/3.png",
  },
  {
    location: "Hella, Iceland",
    rating: "4.96",
    km: "6587",
    availability: "9-16 Apr",
    price: "41,881",
    img: "./images/4.png",
  },
  {
    location: "Volimes, Greece",
    rating: "4.9",
    km: "5587",
    availability: "5-10 Oct",
    price: "16,361",
    img: "./images/5.png",
  },
  {
    location: "Alor Gajah, Malaysia",
    rating: "4.73",
    km: "3456",
    availability: "3-8 Oct",
    price: "34,661",
    img: "./images/6.png",
  },
  {
    location: "Shimla, India",
    rating: "4.77",
    km: "456",
    availability: "1-7 Sep",
    price: "3,161",
    img: "./images/7.png",
  },
  {
    location: "El Nido, Philippines",
    rating: "4.13",
    km: "4876",
    availability: "1-6 Sep",
    price: "12,861",
    img: "./images/8.png",
  },
  {
    location: "Pelkosenniem, Finland",
    rating: "4.81",
    km: "5076",
    availability: "28 Dec-7 Jan",
    price: "13,181",
    img: "./images/9.png",
  },
  {
    location: "Thung Samo, Thailand",
    rating: "New",
    km: "2560",
    availability: "1-6 Sep",
    price: "50,861",
    img: "./images/10.png",
  },
  {
    location: "Cabangan, Philippines",
    rating: "4.67",
    km: "4769",
    availability: "1-6 Sep",
    price: "9,987",
    img: "./images/11.png",
  },
  {
    location: "Harju Country, Estonia",
    rating: "New",
    km: "5134",
    availability: "1-6 Sep",
    price: "4530",
    img: "./images/12.png",
  },
];
